{% set name = "pipefunc" %}
{% set version = "0.50.0" %}
{% set python_min = "3.10" %}

# handle undefined PYTHON in `noarch: generic` outputs
{% if PYTHON is not defined %}{% set PYTHON = "$PYTHON" %}{% endif %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pipefunc-{{ version }}.tar.gz
  sha256: 6e07c380e64c37a186c2c77e98f6957a54ce9c7d176bba9f50239290612fd501

build:
  noarch: python
  number: 1

outputs:
  - name: {{ name }}
    build:
      noarch: generic
      script: {{ PYTHON }} -m pip install . -vv
    requirements:
      host:
        - python {{ python_min }}
        - hatchling
        - wheel
        - versioningit
        - pip
      run:
        - python >={{ python_min }}
        - networkx
        - psutil
        - cloudpickle
        - numpy
    test:
      imports:
        - pipefunc
      commands:
        - pip check
      requires:
        - pip
        - python {{ python_min }}

  - name: {{ name }}-extras
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage(name, max_pin="x.x.x") }}
        - adaptive
        - graphviz
        - graphviz-anywidget
        - griffe
        - ipywidgets
        - matplotlib-base
        - pandas
        - psutil
        - rich
        - xarray
        - zarr
    test:
      imports:
        - pipefunc
      requires:
        - pip
        - python {{ python_min }}

about:
  home: https://github.com/pipefunc/pipefunc
  summary: A Python library for defining, managing, and executing function pipelines.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
