# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/73cd2eed94c576213c5f25ab57adf6d8c83e792a/schema.json
schema_version: 1

context:
  name: "pipefunc"
  version: "0.63.0"
  python_min: "3.10"

recipe:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pipefunc-${{ version }}.tar.gz
  sha256: f7e84ca43f5627fc5f138d5a43a6d16a9437f4f0dd54b615f0bd2828300dc9e5

build:
  number: 0

outputs:
  - package:
      name: ${{ name }}
      version: ${{ version }}
    build:
      noarch: python
      script: ${{ PYTHON }} -m pip install . -vv
    requirements:
      host:
        - python ${{ python_min }}.*
        - hatchling
        - wheel
        - versioningit
        - pip
      run:
        - python >=${{ python_min }}
        - networkx
        - psutil
        - cloudpickle
        - numpy
    tests:
      - python:
          imports:
            - pipefunc

  - package:
      name: ${{ name }}-extras
      version: ${{ version }}
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage(name, exact=True) }}
        - adaptive
        - graphviz
        - graphviz-anywidget
        - griffe
        - ipywidgets
        - matplotlib-base
        - pandas
        - psutil
        - pydantic
        - rich
        - rich-argparse
        - xarray
        - zarr <3
        - bokeh <3.7
    tests:
      - python:
          imports:
            - pipefunc

about:
  homepage: https://github.com/pipefunc/pipefunc
  summary: A Python library for defining, managing, and executing function pipelines.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
